SOURCE CODE/app/urls.py
from django.contrib.auth.views import LogoutView
from django.http import HttpResponse
from django.urls import re_path

from app.views.HomeViews import HomeView, DashboardView
from app.views.Logging.LoggingViews import SystemLogsView, TransactionLogsView, SystemLogsDate, TransactionLogsDate
from app.views.PKI.PKIViews import PkiView, EncryptView, DecryptView, GenerateRSA, UserPublicKeyAPI
from app.views.PiiViews import PiiView, GovtPIIAccess, ViewPii
from app.views.TestViews import TestErrors
from app.views.accounts.AccountViews import UserAccountsView, AccountView, UsersHavingAccountView, \
    UserAddAccountView
from app.views.known_accounts.KnownAccountsViews import EnterKnownAccountsView, ViewKnownAccounts
from app.views.login.LoginViews import MyLoginView
from app.views.payment_accounts.PaymentAccountViews import EnterPaymentAccountsView, ViewPaymentccounts, \
    RemovePaymentAccounts
from app.views.signup.SignUpViews import SignUp, OTPImage, UserConfirmation, \
    PasswordResetConfirm, PasswordResetRequestView
from app.views.JavaScriptDisableViews import JavaScriptDisableView

from app.views.su.SuViews import CustomSuLogout, CustomSuLogin, CustomSuLoginAsUser
from app.views.transactions.TransactionViews import TransactionRequest, TransactionView, \
    TransactionPending, TransactionCompleted, TransactionLocator, TransactionRisky
from app.views.users.UserViews import AllUsersView, UserProfile, UserRequestsReceivedView, \
    UserRequestView, UserProfileEdit, UserDelete

app_name = 'app'

urlpatterns = [
    re_path(r'^robots.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: /", content_type="text/plain")),

    re_path(r'^$', HomeView.as_view(), name='HomeView'),
    re_path(r'^login/$', MyLoginView.as_view(), name='MyLoginView'),
    re_path(r'^logout/$', LogoutView.as_view(), name='LogoutView'),

    re_path(r'^api/superuser/generate-rsa/$', GenerateRSA.as_view(), name='GenerateRSA'),

    re_path(r'^pki/$', PkiView.as_view(), name='PkiView'),
    re_path(r'^api/pki/$', UserPublicKeyAPI.as_view(), name='UserPublicKeyAPI'),
    # re_path(r'^encrypt/$', EncryptView.as_view(), name='EncryptView'),
    # re_path(r'^decrypt/$', DecryptView.as_view(), name='DecryptView'),

    # re_path(r'^change-password/$', ChangePassword.as_view(), name='ChangePassword'),
    re_path(r'^password-reset-initiate/$', PasswordResetRequestView.as_view(), name='PasswordResetRequestView'),
    re_path(r'^password-reset-confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',PasswordResetConfirm.as_view(), name='confirm_password_reset'),

    re_path(r'^signup/$', SignUp.as_view(), name='SignUp'),
    re_path(r'^otp-image/$', OTPImage.as_view(), name='OTPImage'),
    re_path(r'^dashboard/$', DashboardView.as_view(), name='DashboardView'),
  
    re_path(r'^jserror/',JavaScriptDisableView.as_view(), name="JavaScriptDisable"),

    re_path(r'^user/all/$', AllUsersView.as_view(), name='AllUsersView'),
    re_path(r'^user/(?P<user_id>[0-9]+)/$', UserProfile.as_view(), name='UserProfile'),
    re_path(r'^user/(?P<user_id>[0-9]+)/edit/$', UserProfileEdit.as_view(), name='UserProfileEdit'),
    re_path(r'^user/delete/$', UserDelete.as_view(), name='UserDelete'),

    re_path(r'^user/pii/$',ViewPii.as_view(), name='ViewPii'),
    re_path(r'^pii/(?P<user_id>[0-9]+)/$', PiiView.as_view(), name='Pii'),
    re_path(r'^pii/(?P<uidb1>[0-9A-Za-z_\-]+)/(?P<uidb2>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', GovtPIIAccess.as_view(), name='GovtPIIAccess'),

    re_path(r'^enter-known-account/$', EnterKnownAccountsView.as_view(), name='enter_known_account'),
    re_path(r'^view-known-account/$', ViewKnownAccounts.as_view(), name='view_known_account'),
    re_path(r'^enter-payment-account/$', EnterPaymentAccountsView.as_view(), name='enter_payment_account'),
    re_path(r'^view-payment-account/$', ViewPaymentccounts.as_view(), name='view_payment_account'),
    re_path(r'^remove-payment-account/$', RemovePaymentAccounts.as_view(), name='remove_payment_account' ),

    re_path(r'^user/request/$', UserRequestsReceivedView.as_view(), name='UserRequestsReceivedView'),
    re_path(r'^user/request/(?P<user_request_id>[0-9]+)/$', UserRequestView.as_view(), name='UserRequestView'),

    re_path(r'^account/(?P<user_id>[0-9]+)/add/$', UserAddAccountView.as_view(), name='UserAddAccountView'),
    re_path(r'^account/(?P<user_id>[0-9]+)/all/$', UserAccountsView.as_view(), name='UserAccountsView'),
    re_path(r'^account/(?P<user_id>[0-9]+)/(?P<account_id>[0-9]+)/$', AccountView.as_view(), name='AccountView'),
    re_path(r'^account/all/$', UsersHavingAccountView.as_view(), name='UsersHavingAccountView'),

    re_path(r'^transaction/risky/$', TransactionRisky.as_view(), name='TransactionRisky'),
    re_path(r'^transaction/pending/$', TransactionPending.as_view(), name='TransactionPending'),
    re_path(r'^transaction/completed/$', TransactionCompleted.as_view(), name='TransactionCompleted'),
    re_path(r'^transaction/create/$', TransactionRequest.as_view(), name='TransactionRequest'),
    re_path(r'^transaction/(?P<transaction_id>[0-9]+)/$', TransactionView.as_view(), name='TransactionView'),
    re_path(r'^transaction/locator/$', TransactionLocator.as_view(), name='TransactionLocator'),

    re_path(r'^confirm-account/(?P<uidb>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', UserConfirmation.as_view(), name='UserConfirmation'),

    re_path(r'^system-logs-files/$', SystemLogsView.as_view(), name='SystemLogsView'),
    re_path(r'^system-logs/(?P<log_id>[0-9]+)/$', SystemLogsDate.as_view(), name='SystemLogsDate'),
    re_path(r'^transaction-logs-files/$', TransactionLogsView.as_view(), name='TransactionLogsView'),
    re_path(r'^transaction-logs/(?P<log_id>[0-9]+)/$', TransactionLogsDate.as_view(), name='TransactionLogsDate'),

    # Switch User
    re_path(r'^switch-user/$', CustomSuLogout.as_view(), name='CustomSuLogout'),
    re_path(r'^switch-user/login/$', CustomSuLogin.as_view(), name='CustomSuLogin'),
    re_path(r'^switch-user/(?P<user_id>[0-9]+)/$', CustomSuLoginAsUser.as_view(), name='CustomSuLoginAsUser'),

    # Test Errors
    re_path(r'^test-errors/$', TestErrors.as_view(), name='TestErrors'),

    # Include built-in pages for authentication
    # re_path(r'^', include('django.contrib.auth.urls')),
]

SOURCE CODE/bank/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    # TODO: Change to custom page
    # path('admin/', admin.site.urls),

    path('admin/is/the/new/superuser/', admin.site.urls),

    re_path(r'^', include('app.urls')),

    # Session-Security Urls
    re_path(r'^session_security/', include('session_security.urls')),

    # Django-Su Urls
    re_path(r'^switch-user/', include('django_su.urls')),
]

SOURCE CODE/app/forms/LoginForms.py
from django import forms
from django.contrib.auth import user_login_failed
from django.utils.translation import gettext_lazy as _
from django_otp import match_token
from django_otp.forms import OTPAuthenticationForm


class MyAuthenticationForm(OTPAuthenticationForm):

    otp_token = forms.RegexField(
        regex=r'^\d{6}$',
        widget=forms.TextInput(),
        error_messages={
            'invalid': 'Enter a valid otp. Must be 6 digits.'
        }
    )

    error_messages = {
        'invalid_login':
            _("Invalid Credentials.<br>"
              "Please enter a correct username and password.<br>")
        ,
        'inactive': _("This account is inactive."),
    }

    def get_user(self):
        user = self.user_cache

        return user

    def verify(self):
        if self.request.user.is_verified():
            return True

        if not self.request.user.is_authenticated:
            user_login_failed.send(
                sender=self.request.user,
                request=self.request,
                credentials={
                    'username': self.cleaned_data['username']
                }
            )

        return False

    def _verify_token(self, user, token, device=None):
        if device is not None:
            device = device if device.verify_token(token) else None
        else:
            device = match_token(user, token)

        if device is None:
            self.verify()

            raise forms.ValidationError(_('Invalid token. Please make sure you have entered it correctly.'), code='invalid')

        return device

    def __init__(self, request=None, *args, **kwargs):
        super().__init__(request, *args, **kwargs)

        self.fields.pop('otp_device')
        self.fields.pop('otp_challenge')

SOURCE CODE/app/forms/PKIForms.py
from django import forms

from app.models import PublicKey


class PKIForms(forms.ModelForm):

    class Meta:
        model = PublicKey
        fields = ('publickey',)
        labels = {
            'publickey': "Public Key"
        }

SOURCE CODE/app/forms/SignUpForms.py
import random

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from app.models import *
from app.views import CommonHelpers


class PersonalInfo(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(
        attrs={'autofocus': ''}),
        label='First Name',
    )

    phone_number = forms.RegexField(
        regex=r'^\d{10}$',
        widget=forms.TextInput(),
        error_messages={
            'invalid': 'Enter a valid phone number. Must be 10 digits.'
        }
    )

    confirm_email = forms.EmailField(label='Confirm Email')

    years = []
    for year in range(2018, 1900, -1):
        years += [year]

    date_of_birth = forms.DateField(
        widget=forms.SelectDateWidget(
            years=years,
        ),
        label='Date Of Birth',
    )

    USER_TYPE_CHOICES = MyUser.USER_TYPE_CHOICES

    user_type = forms.ChoiceField(widget=forms.RadioSelect, choices=USER_TYPE_CHOICES)

    def __init__(self, created_by, *args, **kwargs):
        self.created_by = created_by

        super(UserCreationForm, self).__init__(*args, **kwargs)
        self.fields.pop('password1')
        self.fields.pop('password2')
        CommonHelpers.help_text_on_hover(self.fields)

    class Meta:
        model = MyUser
        fields = ('first_name', 'last_name', 'username', 'email', 'confirm_email', 'phone_number', 'date_of_birth', 'user_type')
        labels = {
            'last_name': 'Last Name',
            'phone_number': 'Phone Number',
            'email': 'Email Address',
        }

    def clean_date_of_birth(self):
        data = self.cleaned_data['date_of_birth']

        if data > datetime.now().date():
            raise ValidationError('Future Date Invalid', code='future date')

        return data

    def clean_confirm_email(self):
        email1 = self.cleaned_data['email']
        email2 = self.cleaned_data['confirm_email']

        if email1 and email2 and email1 != email2:
            raise ValidationError('Email Does Not Match', code='match email')

        return email2

    def clean_user_type(self):
        user_type = self.cleaned_data['user_type']

        if CommonHelpers.is_int_equal(user_type, MyUser.ADMIN):
            self.created_by = None

        elif CommonHelpers.is_int_equal(user_type, MyUser.EMPLOYEE):
            managers = MyUser.objects.filter(assigned_to=self.created_by, user_type=MyUser.MANAGER)

            if managers:
                index = random.randint(0, len(managers)-1)

                manager = managers[index]
                self.created_by = manager
            else:
                raise ValidationError('Managers do not exist')

        elif CommonHelpers.is_int_equal(user_type, MyUser.INDIVIDUAL_USER) or CommonHelpers.is_int_equal(user_type, MyUser.MERCHANT):
            managers = MyUser.objects.filter(assigned_to=self.created_by, user_type=MyUser.MANAGER)

            temp_managers = []
            for manager in managers:
                employees = MyUser.objects.filter(assigned_to=manager, user_type=MyUser.EMPLOYEE).count()
                if employees > 0:
                    temp_managers += [manager]

            managers = temp_managers

            if managers:
                index = random.randint(0, len(managers)-1)

                manager = managers[index]
                employees = MyUser.objects.filter(assigned_to=manager, user_type=MyUser.EMPLOYEE)

                if employees:
                    index = random.randint(0, len(employees)-1)

                    employee = employees[index]
                    self.created_by = employee
                else:
                    raise ValidationError('Employees do not exist')
            else:
                raise ValidationError('Managers do not exist')

        return user_type

    def save(self, commit=True):
        user = MyUser.objects.create_user(
            self.cleaned_data['username'],
            self.cleaned_data['email'],
            None,
            self.cleaned_data['user_type'],
            self.cleaned_data['first_name'],
            self.cleaned_data['last_name'],
            self.cleaned_data['phone_number'],
            self.cleaned_data['date_of_birth'],
            created_by=self.created_by
        )

        if commit:
            user.save()

        return user


# Unused
class AddressInfo(forms.ModelForm):

    class Meta:
        model = Address
        fields = '__all__'
        labels = {
            'zip': 'Zip Code',
            'house': 'House Address',
            'street': 'Street Address',
        }
        widgets = {
            'house': forms.TextInput(),
            'street': forms.TextInput(),
        }

    def save(self, commit=True):
        address, created = Address.objects.get_or_create(
            house=self.cleaned_data['house'],
            street=self.cleaned_data['street'],
            city=self.cleaned_data['city'],
            zip=self.cleaned_data['zip'],
        )

        if commit:
            address.save()

        return address


class PasswordResetRequestForm(forms.Form):

    user = forms.ModelChoiceField(queryset=MyUser.objects.all().exclude(username=MyUser.ANON).exclude(is_staff=True))

SOURCE CODE/app/views/HomeViews.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.generic.base import View
from app.mixins import LoginAndOTPRequiredMixin
from app.views import CommonHelpers


class HomeView(View):

    def get(self, request):

        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('app:DashboardView'))

        return render(request, 'home.html', {
            'home': True,
        })


class DashboardView(LoginAndOTPRequiredMixin, View):

    def get(self, request):

        user = request.user

        links = []
        balance = None

        if user.is_admin():
            template = 'dashboard.html'
            title = 'Admin'
            links = CommonHelpers.get_admin_links()
        elif user.is_manager():
            template = 'dashboard.html'
            title = 'Manager'
            links = CommonHelpers.get_manager_links()
        elif user.is_employee():
            template = 'dashboard.html'
            title = 'Employee'
            links = CommonHelpers.get_employee_links()
        elif user.is_merchant():
            template = 'dashboard.html'
            title = 'Merchant'
            links = CommonHelpers.get_merchant_links(user.id)
            balance = CommonHelpers.get_user_total_balance(user.id)
        elif user.is_individual_user():
            template = 'dashboard.html'
            title = 'Individual User'
            links = CommonHelpers.get_individual_user_links(user.id)
            balance = CommonHelpers.get_user_total_balance(user.id)
        else:
            template = 'error.html'
            title = ''

        return render(request, template, {
            'title': title,
            'links': links,
            'balance': balance,
        })

SOURCE CODE/app/templates/403_csrf.html
{% include 'error.html' with err='CSRF Failed. Please Try Again.' %}

SOURCE CODE/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		{% load static %}

		{% include 'common_head.html' %}


		{% block head %}{% endblock %}
	</head>
	<body>
		{% if messages %}
			{% for message in messages %}
				<div{% if message.tags %} class="alert alert-{{ message.tags }} alert-dismissable fade show mb-0"{% endif %}>
					{{ message }}

					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
			{% endfor %}
		{% endif %}

		{% block body %}{% endblock %}

		{% include 'common_scripts.html' %}

		{% block body_scripts %}{% endblock %}

		{% include 'su/is_su.html' %}
		{% include 'session_security/all.html' %}

		<div style="height: 10vh;"></div>
	</body>
</html>

SOURCE CODE/app/templates/common_head.html
{% load static %}

<meta charset="UTF-8">

<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

<!-- Vendor CSS Files -->
  <link href="../static/vendor/animate.css/animate.min.css" rel="stylesheet">
  <link href="../static/vendor/aos/aos.css" rel="stylesheet">
  <link href="../static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="../static/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="../static/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="../static/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
  <link href="../static/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="../static/css/style.css" rel="stylesheet">



<link rel="stylesheet" href="{% static 'css/common.css' %}" >

<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

SOURCE CODE/app/templates/filter_template.html
{% extends 'form_template.html' %}

{% block after_form %}

	<div class="mt-5">
		{% for transaction in filter.qs %}
			<div class="h5">
				<a href="{% url 'app:TransactionView' transaction.id %}">
					{{ transaction }}
				</a>
			</div>
		{% endfor %}
	</div>

{% endblock %}

SOURCE CODE/app/templates/form.html
{% load static %}
{% load Filters %}

{% if form.non_field_errors %}
	<div class="d-flex flex-column align-items-center text-center py-1 mb-3">
		{% for error in form.non_field_errors %}
			<small class="text-danger font-weight-bold">{{ error|safe }}</small>
		{% endfor %}
	</div>
{% endif %}

{% for field in form.hidden_fields %}
	{{ field }}
{% endfor %}

{% for field in form.visible_fields %}
	<div class="d-flex w-100 justify-content-center py-1">
		<div class="col-4">
			<span class="d-none">Spacer</span>
		</div>

		<div class="col-2">
			{{ field.label_tag }}
		</div>

		<div class="col-2">
			{% if readonly %}
				{{ field|verbose_value:field.value|default_if_none:"-" }}
			{% else %}
				{{ field }}
			{% endif %}
		</div>

		{% if field.help_text %}
			<small class="d-none">{{ field.help_text }}</small>
		{% endif %}

		<div class="d-flex flex-column col-4 py-1">
			{% if showVirtualKeyboard  %}

				<div id="btn-{{ field.auto_id }}" style="font-size:20px ; cursor:pointer " class="col-1"> &#x2328;</div>
				{% include 'virtualkeyboardhelper.html' with arg=field.auto_id %}

			{% endif %}

			{% for error in field.errors %}
				<small class="text-danger">{{ error }}</small>
			{% endfor %}
		</div>
	</div>
{% endfor %}

SOURCE CODE/app/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
	{% include 'navbar.html' %}

	<div class="d-flex flex-column align-items-center mt-4">

		{% if home %}
			<h1>Welcome To Secure Banking System</h1>
		{% endif %}

		{% block content %}{% endblock %}

	</div>

<!-- ======= Hero Section ======= -->
  <section id="hero" class="d-flex align-items-center">
    <div class="container position-relative text-center text-lg-start" data-aos="zoom-in" data-aos-delay="100">
      <div class="row">
        <div class="col-lg-8">
          <h1>Banking</h1>
          
          <div class="btns">
            <a href="#about" class="btn-menu animated fadeInUp scrollto">Abstract</a>
           
          </div>
        </div>
        

      </div>
    </div>
  </section><!-- End Hero -->

{% endblock %}

SOURCE CODE/app/templates/list_template.html
{% extends 'home.html' %}

{% block content %}

	<h1>{{ title }}</h1>
	{% block information %}{% endblock %}

	<div class="mt-5">

		{% for link in links %}
			<div class="h5">
				<a href="{{ link.1 }}">
					{{ link.0 }}
				</a>
			</div>
		{% endfor %}

	</div>

{% endblock %}

SOURCE CODE/app/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    {% include 'virtualkeyboardscripts.html' %}
{% endblock %}

{% block body %}
	{% include 'navbar.html' %}

	<div class="d-flex flex-column align-items-center mt-4">
		<h1>Login</h1>

		<form method="post" class="mt-5 d-flex flex-column w-100 align-items-center">
			{% csrf_token %}

			{% include 'form.html' with form=form showVirtualKeyboard=True %}

			<hr class="w-50">

			<div class="d-flex w-100 justify-content-center py-1">
				<input type="submit" class="btn btn-dark">
			</div>

		</form>
	</div>
{% endblock %}

SOURCE CODE/app/templates/mail.html
<p>Welcome To SBS</p>
<p>
	Below is a one-time activation link.
	After your email is confirmed, you will be shown a highly sensitive QR Code that will help you set up Google Authenticator for you. Be sure not to share it with anyone.
	This is a required set up. Without this, you will not be able to sign in to your account.
</p>

{% if DEBUG %}
	<a href="http://127.0.0.1:8000{% url 'app:UserConfirmation' uidb token %}">
		http://127.0.0.1:8000{% url 'app:UserConfirmation' uidb token %}
	</a>
{% else %}
	<a href="https://192.168.2.235:443{% url 'app:UserConfirmation' uidb token %}">
		https://192.168.2.235:443{% url 'app:UserConfirmation' uidb token %}
	</a>
{% endif %}

SOURCE CODE/app/templates/mail_passwordreset.html
<p>Welcome To SBS</p>
<p>
	Below is a one-time activation link.
	After your email is confirmed, you will be shown a link where you can set up a password for your account.
    Be sure not to share it with anyone. This is a required set up. Without this, you will not be able to sign in to your account.
</p>

{% if DEBUG %}
	<a href="http://127.0.0.1:8000{% url 'app:confirm_password_reset' uidb64 token %}">
		http://127.0.0.1:8000{% url 'app:confirm_password_reset' uidb64 token %}
	</a>
{% else %}
	<a href="https://192.168.2.235:443{% url 'app:confirm_password_reset' uidb64 token %}">
		https://192.168.2.235:443{% url 'app:confirm_password_reset' uidb64 token %}
	</a>
{% endif %}

SOURCE CODE/app/templates/pii_access_mail.html
<p>
	You have received a request from {{ from_user }} to view PII details of {{ target_user }}.
</p>

{% if DEBUG %}
	<a href="http://127.0.0.1:8000{% url 'app:GovtPIIAccess' uidb1 uidb2 token %}">
		http://127.0.0.1:8000{% url 'app:GovtPIIAccess' uidb1 uidb2 token %}
	</a>
{% else %}
	<a href="https://192.168.2.235:443{% url 'app:GovtPIIAccess' uidb1 uidb2 token %}">
		https://192.168.2.235:443{% url 'app:GovtPIIAccess' uidb1 uidb2 token %}
	</a>
{% endif %}

SOURCE CODE/app/templates/pki.html
{% csrf_token %}

{% if not hideDiv %}
	<div class="d-flex flex-column align-items-center mt-5">
		<p id="div"></p>
	</div>
{% endif %}

<script>

	function generateKeys() {
		encryptDataSaveKey().catch(function () {
			console.log('Could not create RSA key pair');
		});
	}

    async function encryptDataSaveKey() {

	    let keys = await makeKeys();

	    let public_keys = keys.publicKey;
	    let pub_key_object = await crypto.subtle.exportKey("spki", public_keys);
	    let pk = btoa(String.fromCharCode.apply(null, new Uint8Array(pub_key_object)));

	    let private_keys = keys.privateKey;

	    let priv_key_object = await crypto.subtle.exportKey("jwk", private_keys);

	    let final_priv_key =await window.crypto.subtle.importKey(
	        "jwk",
	        {
	            kty: "RSA",
	            e: "AQAB",
	            dp: priv_key_object.dp,
	            dq: priv_key_object.dq,
	            d: priv_key_object.d,
	            n: priv_key_object.n,
	            p: priv_key_object.p,
	            q: priv_key_object.q,
	            qi: priv_key_object.qi,
	            alg: "RSA-OAEP-256",
	            ext: true,
	        },
	        {
	            name: "RSA-OAEP",
	            hash: {name: "SHA-256"},
	        },
	        false,
	        ["decrypt"]
	    );



	    callOnStore(function (store) {
	        store.put({user:'{{ user }}', keys: final_priv_key});
	    });

	    let post= await $.ajax({
			type:"POST",
			url:"{% url 'app:UserPublicKeyAPI' %}",
			data: {
			    'publickey': pk,
			     csrfmiddlewaretoken: '{{ csrf_token }}'
			},
		    success: function () {
			    {% if redirect %}
				    document.getElementById('div').innerText = 'Keys Generated';

				    setTimeout(function () {
					    window.location = '/';
				    }, 1000);
			    {% endif %}
		    }
	    });

    }

    function callOnStore(fn_) {

        var indexedDB = window.indexedDB || window.mozIndexedDB || window.webkitIndexedDB || window.msIndexedDB || window.shimIndexedDB;

        var open = indexedDB.open("SBS", 1);

        open.onupgradeneeded = function() {
            var db = open.result;
            var store = db.createObjectStore("Key", {keyPath: "user"});
            store.createIndex("key_sbs","keys", {unique: true});
        };

        open.onsuccess = function() {
            // Start a new transaction
            var db = open.result;
            var tx = db.transaction("Key", "readwrite");
            var store = tx.objectStore("Key");

            fn_(store);

            tx.oncomplete = function() {
                db.close();
            };
        }
    }

    function makeKeys() {
        return window.crypto.subtle.generateKey(
        {
            name: "RSA-OAEP",
            modulusLength: 1024,
            publicExponent: new Uint8Array([0x01, 0x00, 0x01]),
            hash: {name: "SHA-256"},
        },

        true,
        ["encrypt", "decrypt"]
       )
    }

</script>

SOURCE CODE/app/templates/qrcode.html
{% extends 'base.html' %}

{% block body %}
	{% include 'navbar.html' %}

	{% include 'pki.html' with hideDiv=True %}

	<div class="d-flex flex-column align-items-center mt-4">
		<h1>QR Code</h1>

		<img width="200" height="200"
		     src="{% url "app:OTPImage" %}"
		     onload="generateKeys()"
		>

		<p>or use the URL below:</p>
		<p>{{ device.config_url }}</p>
	</div>
{% endblock %}

SOURCE CODE/app/templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
	{% include 'navbar.html' %}

	<div class="d-flex flex-column align-items-center mt-4">
		<h1>Sign Up</h1>

		<form method="post" class="mt-5 d-flex flex-column w-100 align-items-center">
			{% csrf_token %}

			<p class="font-weight-bold">Personal Details</p>
			{% include 'form.html' with form=form %}

			<hr class="w-50">

			<div class="d-flex w-100 justify-content-center py-1">
				<input type="submit" title="Submit" class="btn btn-dark">
			</div>

		</form>
	</div>
{% endblock %}

{% block body_scripts %}
	<script>
		$(document).ready(function () {
			$('.help-text-on-hover').popover({
				'trigger': 'hover',
				'container': 'body',
				'placement': 'right',
				'html': true,
			});
		})
	</script>
{% endblock %}